### PR TITLE
DevFest Page

### PR DESCRIPTION
**Pull request by KhushilMistry**
I forgot to fork your repo.Instead,I have started working with your repo in source Tree. So Cant be able to make different commit for different changes.

### CODE REVIEW

**Comment by ankit-m** [comment]
@KhushilMistry 
1. What does the page look like? Include screenshots
2. What are those XML files?
3. Explain your code.

**Comment by KhushilMistry** [comment]
Explanation of Code:
->I have added DevFest'16 option in Navbar in Main Page. I have linked it to DevFest.html
**DevFest.Html page**:
->In Devfest.html, The whole content is there. There is a navbar as original page and links to original page. The whole code is devided into 5 division and 4 parallax at end of each section. 
->First division contains an Image(images/GDG_DevFest_Cover.png)(New) and Information about Gdg Devfest.(Screen shot 1).
->After this there is parallax with image (images/b1.jpg)(Old Image)
->There is divison of Topics of talk after it. There is 4 logos of Angular,Firebase,Android N,Polymer(Screen Shot 2). And there is Modal for each Logo(Screenshot 3 and 4).
->After this,There is a Parallax with image(images/b3.jpg)(New).(Screen Shot 5)  
->After this,There is a section for schedule. There is table for schedule.(Screen Shot 5)
->Again there is parallax after this with Image(images/b2.jpg)(Old).(Screenshot 6)
->There is section for speakers after this.I have updated 2 speakers info. I Have used font awesome for LinkedIn,Facebook and Github icon.(Screenshot 6).Images of speakers are from (images/speaker). 
->After this there is another parallax(Image: images/b4.jpg)(New) and after this there is section for Contact us which contains Map,Adreess and contact.(Screenshot 7).

**New things in style.css** : (Scrrenshot 8)(I have not created another file since I am using old components.)
->There 4 major things.
->Class: Padding. I want to add padding in each section so I have created Padding class to give padding to each division.
->Class "topics" and and another class for images "imgspeacker": To give border to image of Speakers.
->Class "padding" Element "i" : To change color of icon to black.
-> Element table,td,tr : To give effect to table in schedule division.

**Changes in init.js**(I have not created another file since I am using old components.)
->New Things: Modal component and carousel(I have not used it in code anywhere..!!).(Scrreenshot 9)

Note: XML files are by default files of source tree.So When we clone any project in SourceTree It will generate this.(Probablay)(I have .idea folder in each Repo which I have cloned through Sourcetree.)(Ignore or delete it.)

**Comment by ankit-m** [comment]
@KhushilMistry The page looks good. Following are the changes you need to make:
1. Remove all XML files, I think they are added by your IDE
2. Remove Polymer (there is no talk on Polymer) and the corresponding `svg` file
3. Angular logo is skewed (correct that)
4. All Google logos are old. You need to find images with new logo. Also, use the official GDG publicity material shared on the group.
5. Attribute all images
6. Change **Topics of Talk** to **Tracks**
7. Add _PWA_ and _Material Design_ as topics
8. Make sure you add commit messages which are readable. Refer [this](http://chris.beams.io/posts/git-commit/) while you write them.

**Comment by KhushilMistry** [comment]
screenshot 57
screenshot 58
screenshot 59
screenshot 60

**Comment by KhushilMistry** [comment]
Is there still any problem ??

**Pull request merged**
