### PR TITLE
Updated Schedule and Speakers info

### PR DESCRIPTION
**Pull request by KhushilMistry**

### CODE REVIEW

**Comment by KhushilMistry** [comment]
screenshot 64
screenshot 65

**Comment by ankit-m** [comment]
In the afternoon schedule, it says 2 am to 4 am. Please change it to pm

**Comment by KhushilMistry** [comment]
screenshot 66

**Comment by KhushilMistry** [comment]
There is one problem on Current wesite. In the Modal of AnglarJS , logo of Angular is not there(Error). Check it. 
screenshot 67

**Pull request merged**
